ALTER TABLE "Event" DROP COLUMN "category",
DROP COLUMN "interests",
DROP COLUMN "mode",
DROP COLUMN "skills",
ADD COLUMN     "cashPrize" DOUBLE PRECISION,
ADD COLUMN     "certificateAvailable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "contactEmail" TEXT,
ADD COLUMN     "contactNumber" TEXT,
ADD COLUMN     "domain" TEXT,
ADD COLUMN     "endTime" TEXT,
ADD COLUMN     "organizerDepartment" TEXT,
ADD COLUMN     "organizerName" TEXT,
ADD COLUMN     "posterUrl" TEXT,
ADD COLUMN     "registrationDeadline" TIMESTAMP(3),
ADD COLUMN     "registrationFee" DOUBLE PRECISION,
ADD COLUMN     "startTime" TEXT,
ADD COLUMN     "whatsappGroupLink" TEXT;
ALTER TABLE "User" DROP COLUMN "careerGoal",
DROP COLUMN "location",
ADD COLUMN     "preferredMode" TEXT NOT NULL,
DROP COLUMN "preferredEventType",
ADD COLUMN     "preferredEventType" TEXT[],
DROP COLUMN "skills",
ADD COLUMN     "skills" TEXT[],
DROP COLUMN "interests",
ADD COLUMN     "interests" TEXT[];
